### ISSUE TITLE
App opens web page in browser instead

### ISSUE THREAD

**Issue by wolfm89** [92lleo/WhatsappWebToGo#28]
Hi,

first of all big thanks for creating this awesome app!

There is a single problem for me that is a bit annoying: Sometimes when I open the app a browser window is opened instead and directs me to the WhatsApp Web page. When I then close the browser and open the app again it only shows a blank screen and doesn't load. I have to force stop it and restart the application in order for it to work again.

Any idea what the problem could be? I'm using the app on my Samsung Galaxy Tab S7+.

Best,
Wolfgang

**Comment by 92lleo** [comment]
Hi,
sometimes WA Web detects a mobile phone browser (within the app), then redirects to the whatsapp web page, which opens externally like any other link. **Instead of force closing, you can use "reload" from the navigation drawer.** 
The redicting to the whatsapp page should be stopped automatically though.. I'll look into it. Will take some time b/c of holidays🌴. I'll keep this issue updated
